#!/bin/sh

chmod 500 /usr/share/${project.artifactId}/*.jar

ln -fs /usr/share/${project.artifactId}/${project.artifactId}.jar /etc/init.d/${project.artifactId}

update-rc.d ${project.artifactId} defaults
service ${project.artifactId} start
